Repository mash-up-kr/Nawa-Invitation-Backend, pull requests merged in 2020-08, with the labels that each got.

#35 [Fix] 초대장 해쉬코드 버그 해결 및 초대장 덤프데이터 추가
  src/main/java/com/mashup/backend/nawa_invitation_project/common/customUtil/CustomUtil.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/controller/InvitationController.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/InvitationRepository.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/controller/UserController.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/service/UserService.java
Labels: ☝️version 1.0.0, 🐞bug, 💪enhancement

#40 템플릿 유형별 사용자의 초대장 존재 유무 로직 수정
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/controller/InvitationController.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/InvitationRepository.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/service/InvitationService.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/service/TemplateService.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/service/UserService.java
Labels: ⛑refactor, 💪enhancement

#45 무중단 자동 배포를 위한 스크립트 작성
  Dockerfile_nawa
  Dockerfile_nginx
  deploy.sh
  docker-compose.yml
  gradlew
  nginx.conf
Labels: 🎊feature

#46 배포 스크립트 수정
  deploy.sh
Labels: 💪enhancement
