Repository mash-up-kr/Nawa-Invitation-Backend, pull requests merged in 2020-07, with the labels that each got.

#8 프로젝트 네이밍 관련사항 수정
  README.md
  settings.gradle
  src/main/java/com/mashup/backend/nawa_invitation_project/NawaInvitationApplication.java
Labels: ⛑refactor, 🧾documentation

#12 User 도메인 패키지 구조 생성 및 User Entity 생성
  src/main/java/com/mashup/backend/nawa_invitation_project/common/domain/BaseTimeEntity.java
  src/main/java/com/mashup/backend/nawa_invitation_project/config/JpaConfig.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/domain/User.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/domain/UserRepository.java
  src/test/java/com/mashup/backend/nawa_invitation_project/user/UserTest.java
Labels: ☝️version 1.0.0, 🎊feature

#11 application.yml 설정 파일 추가
  src/main/resources/application.yml
Labels: 💪enhancement

#15 Template 도메인 패키지 구조와 Template Entity 생성
  src/main/java/com/mashup/backend/nawa_invitation_project/template/controller/.keep
  src/main/java/com/mashup/backend/nawa_invitation_project/template/domain/Template.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/domain/TemplateRepository.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/dto/request/.keep
  src/main/java/com/mashup/backend/nawa_invitation_project/template/dto/response/.keep
  src/main/java/com/mashup/backend/nawa_invitation_project/template/exception/.keep
  src/main/java/com/mashup/backend/nawa_invitation_project/template/service/.keep
  src/test/java/com/mashup/backend/nawa_invitation_project/template/TemplateTest.java
Labels: ☝️version 1.0.0, 🎊feature

#18 기존 코드에 구글 스타일 코드 적용
  src/main/java/com/mashup/backend/nawa_invitation_project/NawaInvitationApplication.java
  src/main/java/com/mashup/backend/nawa_invitation_project/common/domain/BaseTimeEntity.java
  src/main/java/com/mashup/backend/nawa_invitation_project/config/JpaConfig.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/domain/Template.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/domain/TemplateRepository.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/domain/User.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/domain/UserRepository.java
  src/test/java/com/mashup/backend/nawa_invitation_project/user/UserTest.java
Labels: ⛑refactor

#19 [Feat] Implement Invitation Entity and Repository
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/Invitation.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/InvitationRepository.java
Labels: ☝️version 1.0.0, 🎊feature

#22 [Feat] Implement SwaggerConfig
  src/main/java/com/mashup/backend/nawa_invitation_project/config/SwaggerConfig.java
Labels: 🎊feature

#21 [Fix] Fix Invitation Entity bug
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/Invitation.java
Labels: 🐞bug

#23 초대장 유형 리스트 API
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/Invitation.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/InvitationRepository.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/controller/.keep
  src/main/java/com/mashup/backend/nawa_invitation_project/template/controller/TemplateController.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/domain/Template.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/domain/TemplateRepository.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/dto/request/.keep
  src/main/java/com/mashup/backend/nawa_invitation_project/template/dto/request/ReqInvitationTypeListDto.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/dto/response/.keep
  src/main/java/com/mashup/backend/nawa_invitation_project/template/dto/response/ResInvitationTypeItemDto.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/dto/response/ResInvitationTypeListDto.java
  src/main/java/com/mashup/backend/nawa_invitation_project/template/service/.keep
  src/main/java/com/mashup/backend/nawa_invitation_project/template/service/TemplateService.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/domain/User.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/domain/UserRepository.java
  src/test/java/com/mashup/backend/nawa_invitation_project/template/domain/TemplateControllerTest.java
  src/test/java/com/mashup/backend/nawa_invitation_project/template/domain/TemplateTest.java
Labels: ☝️version 1.0.0, 🎊feature

#24 초대장 정보 수정 관련 api 의사 코드 구현 및 스웨거 문서 작성
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/controller/InvitationController.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/Invitation.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/InvitationRepository.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/dto/InvitationAddressRequestDto.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/dto/InvitationTimeRequestDto.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/dto/InvitationWordsRequestDto.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/service/InvitationService.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/domain/UserRepository.java
Labels: 🎊feature, 🧾documentation

#27 첫화면 유저정보 유무 체크 후 생성
  src/main/java/com/mashup/backend/nawa_invitation_project/common/customUtil/CustomUtil.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/Invitation.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/controller/UserController.java
  src/main/java/com/mashup/backend/nawa_invitation_project/user/service/UserService.java
Labels: 🎊feature

#29 초대장 날짜/시간 업데이트 API 비즈니스로직 구현
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/controller/InvitationController.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/domain/Invitation.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/dto/request/InvitationTimeRequestDto.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/dto/response/ResDetailInvitationDto.java
  src/main/java/com/mashup/backend/nawa_invitation_project/invitation/service/InvitationService.java
Labels: ☝️version 1.0.0, 🎊feature, 💪enhancement
